version: '3'

services:
  sensu-server:
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "4567:4567"
    image: sensu-server:latest
    restart: always
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_VHOST: /sensu
      RABBITMQ_USERNAME: sensu
      RABBITMQ_PASSWORD: sensu
      REDIS_HOSTNAME: redis
      REDIS_PASSWORD: redis
    networks:
      - sensu
  redis:
    image: redis:latest
    restart: always
    networks:
      - sensu
  rabbitmq:
    image: rabbitmq:3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: sensu
      RABBITMQ_DEFAULT_PASS: sensu
      RABBITMQ_DEFAULT_VHOST: /sensu
    networks:
      - sensu
  uchiwa:
    depends_on:
      - sensu-server
    ports:
      - "3000:3000"
    image: uchiwa:latest
    restart: always
    environment:
      SENSUENV_HOST: sensu-server
    networks:
      - sensu
  sensu-client:
    depends_on:
      - sensu-server
    image: sensu-client:latest
    restart: always
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_VHOST: /sensu
      RABBITMQ_USERNAME: sensu
      RABBITMQ_PASSWORD: sensu
    networks:
      - sensu
networks:
  sensu:
    driver: bridge