apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.6.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: sensu
        - name: RABBITMQ_DEFAULT_USER
          value: sensu
        - name: RABBITMQ_DEFAULT_VHOST
          value: /sensu
        image: rabbitmq:3
        name: rabbitmq
        resources: {}
      restartPolicy: Always
status: {}
